language: ruby

# Enabling Bundler caching
cache:
  - bundler

# When not explicitely specified Travis CI will relay on a .ruby-version
# rvm:
  # - 3.0.1
  # - 2.6.7
  # - 2.7.1

# Option to use Bundler 2.x
before_install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rspec spec


